@extends('layouts.app')

@section('content')
    <x-hero 
        :heroContent="$heroContent" 
        :techStackSkills="$techStackSkills"
        :user="$user"
    />
    <x-about 
        :aboutContent="$aboutContent"
        :user="$user"
    />
    <x-projects 
        :projects="$projects"
        :user="$user"
    />
    <x-skills 
        :skills="$skills"
        :user="$user"
    />
    <x-experience 
        :experiences="$experiences"
        :user="$user"
    />
    <x-education 
        :educations="$educations"
        :user="$user"
    />
    <x-contact 
        :contactContent="$contactContent"
        :user="$user"
    />
@endsection