cat > nixpacks.toml << 'EOF'
[phases.setup]
nixPkgs = [
  'php82',
  'php82Extensions.intl',
  'php82Extensions.zip',
  'php82Extensions.pdo',
  'php82Extensions.pdo_mysql',
  'php82Extensions.mbstring',
  'php82Extensions.xml',
  'php82Extensions.curl',
  'php82Extensions.gd',
  'php82Extensions.fileinfo',
  'php82Extensions.tokenizer',
  'php82Extensions.bcmath',
  'php82Extensions.ctype',
  'php82Extensions.dom',
  'php82Extensions.filter',
  'php82Extensions.hash',
  'php82Extensions.openssl',
  'php82Extensions.pcre',
  'php82Extensions.session'
]

[phases.install]
cmds = ['composer install --optimize-autoloader --no-dev --no-interaction']

[phases.build]
cmds = [
  'npm ci',
  'npm run build',
  'php artisan config:cache',
  'php artisan route:cache',
  'php artisan view:cache'
]

[start]
cmd = 'php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT'
EOF