[phases.setup]
nixPkgs = ['php82', 'php82Extensions.intl', 'php82Extensions.zip', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.mbstring', 'php82Extensions.xml', 'php82Extensions.curl', 'php82Extensions.gd', 'php82Extensions.fileinfo', 'php82Extensions.tokenizer']

[phases.install]
cmds = ['composer install --optimize-autoloader --no-dev --no-interaction']

[phases.build]
cmds = ['php artisan config:cache', 'php artisan route:cache', 'php artisan view:cache']

[start]
cmd = 'php artisan migrate --force && php -S 0.0.0.0:$PORT -t public'